FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir redis==8.1.0 "psycopg[binary]==3.3.6"
COPY common ./common
COPY worker ./worker
ENV PYTHONUNBUFFERED=1
CMD ["python", "-m", "worker.worker"]
